### ISSUE TITLE
checking for note combinations?

### ISSUE THREAD

**Issue by d-vyd** [edouardtheron/py-midi#10]
Hello,
Thank you for creating this library. Are there some more examples available anywhere? I'd like to create a custom interface to my MIDI controller that detects if a certain combination of notes are sent at the same time (buttons pushed together) and then sends a different note, possibly on a different channel. The script would just be a series of "if" statements checking for different note combinations.
-da'ud

**Comment by edouardtheron** [comment]
Hello,

Sorry for a late reply. I think the MIDI standard does not support notes sent at the same time, but because of the high baudrate, the human ear can't notice it.

Some manufacturer may have developed custom solutions for that — on top of MIDI standards — but this library, in its current state, won't be able to help you here.

**Comment by d-vyd** [comment]
Thank you. In the library's current state, is it possible to detect if two specific notes are pressed nearly at the same time (say less than 1/10 second a part)?


________________________________

**Comment by edouardtheron** [comment]
You can get a much finer resolution than 1/10th of a second (about two orders of magnitude finer actually)

As per the MIDI standard, the serial interface transmits data at a rate of 31250 bits per second. A typical MIDI message being 3 bytes, you can send about 1300 messages in one second. 

By default, this library respects the MIDI standard of 31250 bits/sec. If required, you can customize the baudrate when you [instantiate the connector](https://github.com/edouardtheron/py-midi/blob/master/midi/midi.py#L140).

**Comment by d-vyd** [comment]
Thanks. I'll give it a try!

On Sep 23, 2019 11:14 AM, Edouard Theron <notifications@github.com> wrote:

You can get a much finer resolution than 1/10th of a second (about two orders of magnitude finer actually)

As per the MIDI standard, the serial interface transmits data at a rate of 31250 bits per second. A typical MIDI message being 3 bytes, you can send about 1300 messages in one second.

By default, this library respects the MIDI standard of 31250 bits/sec. If required, you can customize the baudrate when you instantiate the connector<https://github.com/edouardtheron/py-midi/blob/master/midi/midi.py#L140>.
