### ISSUE TITLE
problem with "conn.write(msg)"

### ISSUE THREAD

**Issue by Elninaar** [edouardtheron/py-midi#11]
Hello,
I'm trying to send midi messages from a Raspberry Pi 3B + with the latest version of python.
All seems to work fine but when I made the command:
conn.write (msg)
I do not get the value of the number of bytes sent and the MIDI message is not sent.

If anyone has a solution I would be eternally grateful to him!

**Comment by edouardtheron** [comment]
@Elninaar that's odd.

Does the `read` method work as expected?

Do you have any error message?

Can you share the code where you instantiate your `msg` variable?

**Comment by Elninaar** [comment]
I'm sorry to disturb you. it was my fault .. 
The serial port of my Raspberry was not able to send data.. now it works perfectly!
Thank you for your work!!

**Comment by edouardtheron** [comment]
Glad it worked :wink:
