### ISSUE TITLE
Is there a way to access USB connected MIDI devices / Ports ?

### ISSUE THREAD

**Issue by dschiller** [edouardtheron/py-midi#14]
Is there a way to access USB connected MIDI devices / Ports ?

I checked the `/dev` folder but nothing looks like my connected MIDI device.

**Comment by LoicGRENON** [comment]
What kind of device are you trying to access to ?
Do you mind to share the output of `lsusb -l` ?

An USB device requires a driver to translate the commands and data between the host and the peripheral.
If your USB device doesn't expose a serial port, it means it won't be supported by this library.

**Comment by dschiller** [comment]
It's a NI USB Audio Card which has MIDI In Port where a Clavia nordwave is connected.

This ticket can be closed I switched to rtmidi ( https://pypi.org/project/python-rtmidi )
