### ISSUE TITLE
SysHex error

### ISSUE THREAD

**Issue by postagiacomini** [edouardtheron/py-midi#5]
I found a possible bug for SysEx, and try to fix it.
In midi.py (310), instead of i message.type != SysEx :
if message.type.\_\_class\_\_ != SysEx :

Hope it will be usefull to someone

**Comment by edouardtheron** [comment]
@postagiacomini  this must have been solved with 35190e18e78

It is not merged with `master` yet, as it need to be tested first...

**Comment by edouardtheron** [comment]
@postagiacomini closing this issue as this is now solved on `master`.

There is a new release 2.0, which must be more solid that the previous.
