### ISSUE TITLE
Importing py-midi conflict with another python MIDI library

### ISSUE THREAD

**Issue by edavalosanaya** [edouardtheron/py-midi#7]
Hello,

Sorry if I am forgetting something that might resolve this issue instantly. The current problem that I am having is that I am attempting to use this library and another library called python midi (https://github.com/vishnubob/python-midi) for the same project. The issue is that both libraries utilize [import midi] to call upon the module. I considered manually going into the py-midi library and changing the label to make both libraries functional. Currently, I do not have access to any of the functionality of the py-midi library since [import midi] will only import the python midi library. 

My code:

import midi
c = MidiConnector('/dev/serial0') 

Output:

c = MidiConnector('/dev/serial0') 
NameError: name 'MidiConnector' is not defined

I assume that that the import midi is importing the other midi module; therefore, causing the py-midi library not being imported and causing the NameError.

Thank you for your time.

**Comment by edouardtheron** [comment]
Sorry for replying late. 

Just try using aliasing, and it should be fine, or import only the object you need...Eg:

```python
from midi import MidiConnector
c = MidiConnector('/dev/serial0')
```

or 
```python
import midi as midi_lib
c = midi_lib.MidiConnector('/dev/...')
```
